name: tests

on:
  push:

env:
  WAREHOUSE_HOST: ${{ secrets.WAREHOUSE_HOST }}
  WAREHOUSE_APIKEY: ${{ secrets.WAREHOUSE_APIKEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        pip install pytest
        python -m pytest -s tests
